# Generated by Django 2.0.5 on 2018-05-15 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phone', '__first__'),
        ('appuser', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESTRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=1)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phone.Phone')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appuser.Appuser')),
            ],
        ),
    ]
