# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-11 11:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appuser',
            fields=[
                ('uid', models.AutoField(auto_created=True, help_text='ID that can uniquely identify user', primary_key=True, serialize=False, verbose_name='user id')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='email of user')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
